"""
GitHub Pull Request integration (v2.10.0).

After Gate 3 approval the tool automatically:
  1. Creates a branch:  informatica/{mapping_name_slug}/{job_id_short}
  2. Commits all generated code and test files to that branch
  3. Opens a draft PR against the configured base branch with a structured
     description covering stack, complexity, coverage, equivalence, and
     the three human-review decisions.

Configuration (.env):
  GITHUB_TOKEN        Personal Access Token or GitHub App token (required)
  GITHUB_REPO         "owner/repo" or "org/repo"            (required)
  GITHUB_BASE_BRANCH  Target branch for PRs (default: main)
  GITHUB_API_URL      Override for GitHub Enterprise Server
                      (default: https://api.github.com)

All failures are non-fatal — if PR creation fails the job still completes
and the error is logged as a warning.  The PR URL is stored in state under
state["pr_url"] when creation succeeds.
"""
from __future__ import annotations

import base64
import logging
import re
from datetime import datetime, timezone

import httpx

from .config import settings

_log = logging.getLogger("conversion.git_pr")


# ── Helpers ──────────────────────────────────────────────────────────────────

def _slug(text: str) -> str:
    """Convert arbitrary text to a safe git branch name segment."""
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return s[:50] or "mapping"


def _headers() -> dict:
    return {
        "Authorization":        f"Bearer {settings.github_token}",
        "Accept":               "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent":           f"Informatica-Conversion-Tool/{settings.app_version}",
    }


def _api(path: str) -> str:
    base = settings.github_api_url.rstrip("/")
    repo = settings.github_repo.strip("/")
    return f"{base}/repos/{repo}/{path.lstrip('/')}"


# ── PR description builder ────────────────────────────────────────────────────

def _build_pr_body(state: dict, filename: str, branch: str) -> str:
    from .models.schemas import ConversionOutput, ParseReport

    conv    = state.get("conversion", {})
    review  = state.get("code_review", {})
    tests   = state.get("test_report", {})
    recon   = state.get("reconciliation", {})
    sign1   = state.get("sign_off", {})
    sign2   = state.get("security_sign_off", {})
    sign3   = state.get("code_sign_off", {})
    parse   = state.get("parse_report", {})
    complex_ = state.get("complexity", {})

    mapping_name  = conv.get("mapping_name", filename)
    target_stack  = conv.get("target_stack", "unknown")
    tier          = complex_.get("tier", "unknown")
    parse_ok      = conv.get("parse_ok", True)

    # Gate reviewers
    r1 = sign1.get("reviewer_name", "—")
    r2 = sign2.get("reviewer_name", "—") if sign2 else "auto-approved (clean scan)"
    r3 = sign3.get("reviewer_name", "—")

    # Test coverage
    cov_pct      = tests.get("coverage_pct", 0)
    fields_cov   = tests.get("fields_covered", 0)
    fields_miss  = tests.get("fields_missing", 0)

    # Equivalence
    eq = review.get("equivalence_report") or {}
    eq_v  = eq.get("total_verified", "—")
    eq_nr = eq.get("total_needs_review", "—")
    eq_m  = eq.get("total_mismatches", "—")

    # Reconciliation
    rec_status = recon.get("final_status", "—")
    rec_rate   = recon.get("match_rate", 0)

    # Code review
    rec_cr = review.get("recommendation", "—")
    checks_pass = review.get("total_passed", "—")
    checks_fail = review.get("total_failed", "—")

    # Generated files
    files = conv.get("files", {})
    test_files = tests.get("test_files", {})
    file_list = "\n".join(f"- `{f}`" for f in sorted(files.keys()))
    test_list = "\n".join(f"- `{f}`" for f in sorted(test_files.keys())) if test_files else "_none_"

    # Parse degraded warning
    degraded_note = (
        "\n> ⚠️ **Parse degraded** — some source fields could not be fully resolved. "
        "Review TODO stubs before merging.\n"
        if not parse_ok else ""
    )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""## Informatica Conversion: `{mapping_name}`

Automatically generated by the **Informatica Conversion Tool v{settings.app_version}**.
Branch: `{branch}`
{degraded_note}
---

### Mapping Details

| Property | Value |
|---|---|
| **Source file** | `{filename}` |
| **Target stack** | {target_stack} |
| **Complexity tier** | {tier} |

### Quality Summary

| Check | Result |
|---|---|
| **Test coverage** | {cov_pct}% ({fields_cov} covered / {fields_miss} missing) |
| **Code review** | {rec_cr} ({checks_pass} passed / {checks_fail} failed) |
| **Logic equivalence** | {eq_v} verified / {eq_nr} needs review / {eq_m} mismatches |
| **Structural reconciliation** | {rec_status} ({rec_rate:.1f}% match rate) |

### Generated Files

**Code**
{file_list or '_none_'}

**Tests**
{test_list}

### Review Gates

| Gate | Decision | Reviewer |
|---|---|---|
| Gate 1 — Human Sign-off | ✅ APPROVED | {r1} |
| Gate 2 — Security Review | ✅ {sign2.get('decision', 'APPROVED') if sign2 else 'APPROVED'} | {r2} |
| Gate 3 — Code Sign-off | ✅ APPROVED | {r3} |

---
*Generated {now} · Job ID: `{state.get('job_id', '—')}`*
*[Informatica Conversion Tool](https://github.com/ad25343/InformaticaConversion)*
"""


# ── Main entry point ──────────────────────────────────────────────────────────

async def create_pull_request(job_id: str, state: dict, filename: str) -> str | None:
    """
    Create a GitHub PR for the approved conversion job.

    Returns the PR URL on success, None on failure or if not configured.
    All exceptions are caught — this function is always non-fatal.
    """
    if not settings.github_token or not settings.github_repo:
        _log.debug("GitHub PR: not configured (GITHUB_TOKEN or GITHUB_REPO not set) — skipping.")
        return None

    conv       = state.get("conversion", {})
    tests      = state.get("test_report", {})
    mapping_name = conv.get("mapping_name", filename.replace(".xml", ""))

    branch = f"informatica/{_slug(mapping_name)}/{job_id[:8]}"
    base   = settings.github_base_branch

    try:
        async with httpx.AsyncClient(
            headers=_headers(),
            timeout=30,
        ) as client:

            # ── 1. Get the SHA of the base branch ──────────────────────────
            r = await client.get(_api(f"git/ref/heads/{base}"))
            if r.status_code == 404:
                _log.warning("GitHub PR: base branch '%s' not found in %s — skipping.",
                             base, settings.github_repo)
                return None
            r.raise_for_status()
            base_sha = r.json()["object"]["sha"]

            # ── 2. Create the new branch ────────────────────────────────────
            r = await client.post(_api("git/refs"), json={
                "ref": f"refs/heads/{branch}",
                "sha": base_sha,
            })
            if r.status_code == 422:
                # Branch already exists — that's fine, we'll push to it
                _log.info("GitHub PR: branch '%s' already exists — reusing.", branch)
            else:
                r.raise_for_status()

            # ── 3. Commit all generated files ───────────────────────────────
            files_committed: list[str] = []

            all_files: dict[str, str] = {}
            all_files.update(conv.get("files", {}))
            all_files.update(tests.get("test_files", {}))

            for filepath, content in all_files.items():
                encoded = base64.b64encode(content.encode()).decode()
                # Check if file already exists on branch (needed for SHA)
                existing = await client.get(_api(f"contents/{filepath}"),
                                            params={"ref": branch})
                payload: dict = {
                    "message": f"feat: add {filepath} from Informatica conversion",
                    "content": encoded,
                    "branch":  branch,
                }
                if existing.status_code == 200:
                    payload["sha"] = existing.json()["sha"]

                r = await client.put(_api(f"contents/{filepath}"), json=payload)
                r.raise_for_status()
                files_committed.append(filepath)

            _log.info("GitHub PR: committed %d file(s) to branch '%s'.",
                      len(files_committed), branch)

            # ── 4. Open the pull request ────────────────────────────────────
            pr_body = _build_pr_body(state | {"job_id": job_id}, filename, branch)
            r = await client.post(_api("pulls"), json={
                "title": f"[Informatica] {mapping_name}",
                "head":  branch,
                "base":  base,
                "body":  pr_body,
                "draft": True,   # Draft so it's clearly a generated artefact
            })
            if r.status_code == 422 and "pull request already exists" in r.text.lower():
                _log.info("GitHub PR: PR already open for branch '%s' — skipping.", branch)
                return None
            r.raise_for_status()

            pr_url = r.json()["html_url"]
            _log.info("GitHub PR created: %s", pr_url)
            return pr_url

    except httpx.HTTPStatusError as exc:
        _log.warning(
            "GitHub PR: HTTP error %d — %s (non-fatal)",
            exc.response.status_code, exc.response.text[:300],
        )
    except Exception as exc:
        _log.warning("GitHub PR: failed (non-fatal) — %s", exc)

    return None
