"""
golden_compare.py — Component B of v2.13 Data-Level Equivalence Testing
========================================================================

Generates a self-contained Python comparison script (`tests/compare_golden.py`)
that is included in every conversion job's test output.

The generated script requires only stdlib + pandas and runs entirely outside
the conversion tool. Data engineers run it after:
  1. Capturing Informatica's output as a CSV (golden reference)
  2. Running the generated code against the same input rows and capturing output

Usage of the generated script:
  python tests/compare_golden.py \\
    --expected informatica_output.csv \\
    --actual   generated_code_output.csv \\
    [--threshold 99.5] \\
    [--key-columns ACCOUNT_ID,LOAD_DATE] \\
    [--ignore-columns AUDIT_TIMESTAMP,ETL_RUN_ID]
"""
from __future__ import annotations
from datetime import datetime, timezone


def generate_comparison_script(mapping_name: str) -> str:
    """
    Return the full source code of a self-contained compare_golden.py script
    customised for the given mapping.

    Parameters
    ----------
    mapping_name : str
        The Informatica mapping name (used in report headers and default filenames).

    Returns
    -------
    str
        Complete Python script content ready to be written as tests/compare_golden.py.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    safe_name = mapping_name.replace('"', '\\"')

    return f'''#!/usr/bin/env python3
"""
compare_golden.py — Golden Output Comparison Script
=====================================================
Auto-generated by Informatica Conversion Tool v2.13.0
Mapping : {safe_name}
Generated: {ts}

PURPOSE
-------
Compare the output CSV captured from Informatica (the "golden" reference) against
the CSV produced by running the generated code.  Run this script after:

  1. Capturing a sample of Informatica session output and saving it as a CSV.
  2. Running the converted code (dbt model / PySpark script / SQL) against the
     SAME source rows and capturing its output as a CSV.

USAGE
-----
  python tests/compare_golden.py \\
    --expected informatica_output.csv \\
    --actual   generated_code_output.csv \\
    [--threshold 99.5] \\
    [--key-columns ACCOUNT_ID,LOAD_DATE] \\
    [--ignore-columns AUDIT_TIMESTAMP,ETL_RUN_ID]

ARGUMENTS
---------
  --expected        Path to the Informatica golden-output CSV  (required)
  --actual          Path to the generated-code output CSV      (required)
  --threshold       Minimum row-match % to pass (default: 100.0)
  --key-columns     Comma-separated columns for row-level join (auto-detected if omitted)
  --ignore-columns  Comma-separated columns to skip entirely   (e.g. audit timestamps)

EXIT CODES
----------
  0  All checks pass within threshold
  1  One or more checks fail or threshold not met

REQUIREMENTS
------------
  pip install pandas
  (No other dependencies — this script is self-contained)
"""
from __future__ import annotations

import argparse
import math
import sys
from typing import Optional

try:
    import pandas as pd
except ImportError:
    print("ERROR: pandas is required.  Install with: pip install pandas", file=sys.stderr)
    sys.exit(1)


# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

MAPPING_NAME   = "{safe_name}"
FLOAT_RTOL     = 1e-5   # relative tolerance for float comparisons
FLOAT_ATOL     = 1e-8   # absolute tolerance for float comparisons
MISMATCH_LIMIT = 20     # max mismatch rows shown in report


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    args = _parse_args()

    key_cols    = [c.strip() for c in args.key_columns.split(",")]    if args.key_columns    else []
    ignore_cols = [c.strip() for c in args.ignore_columns.split(",")]  if args.ignore_columns else []

    print(_banner("GOLDEN COMPARISON REPORT"))
    print(f"  Mapping  : {{MAPPING_NAME}}")
    print(f"  Generated: {{pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}}")
    print(f"  Expected : {{args.expected}}")
    print(f"  Actual   : {{args.actual}}")
    print(f"  Threshold: {{args.threshold}}%")
    if ignore_cols:
        print(f"  Ignoring : {{', '.join(ignore_cols)}}")
    print()

    # ── Load CSVs ────────────────────────────────────────────────────────────
    try:
        df_exp = pd.read_csv(args.expected, dtype=str)
        df_act = pd.read_csv(args.actual,   dtype=str)
    except FileNotFoundError as e:
        print(f"ERROR: {{e}}", file=sys.stderr)
        sys.exit(1)

    # Drop ignored columns
    df_exp = df_exp.drop(columns=[c for c in ignore_cols if c in df_exp.columns], errors="ignore")
    df_act = df_act.drop(columns=[c for c in ignore_cols if c in df_act.columns], errors="ignore")

    # Normalise column names: strip whitespace, uppercase
    df_exp.columns = [c.strip().upper() for c in df_exp.columns]
    df_act.columns = [c.strip().upper() for c in df_act.columns]
    key_cols       = [c.upper() for c in key_cols]
    ignore_cols    = [c.upper() for c in ignore_cols]

    all_pass = True

    # ── Row count ─────────────────────────────────────────────────────────────
    print(_section("ROW COUNTS"))
    exp_rows, act_rows = len(df_exp), len(df_act)
    count_match = exp_rows == act_rows
    print(f"  Expected (Informatica) : {{exp_rows:,}} rows")
    print(f"  Actual (Generated code): {{act_rows:,}} rows")
    if count_match:
        print("  Match                  : ✓ Equal")
    else:
        diff = act_rows - exp_rows
        direction = "more" if diff > 0 else "fewer"
        hint = (
            "Possible fan-out — check JOIN conditions for inadvertent cartesian product"
            if diff > 0
            else "Possible data loss — check filter conditions and NULL handling"
        )
        print(f"  Match                  : ✗ {{abs(diff):,}} {{direction}} rows in actual")
        print(f"  Likely cause           : {{hint}}")
        all_pass = False
    print()

    # ── Schema comparison ────────────────────────────────────────────────────
    print(_section("SCHEMA"))
    exp_cols = set(df_exp.columns)
    act_cols = set(df_act.columns)
    missing  = sorted(exp_cols - act_cols)
    extra    = sorted(act_cols - exp_cols)
    common   = sorted(exp_cols & act_cols)

    print(f"  Columns in expected : {{len(exp_cols)}}")
    print(f"  Columns in actual   : {{len(act_cols)}}")
    print(f"  Missing from actual : {{', '.join(missing) if missing else 'none'}}")
    print(f"  Extra in actual     : {{', '.join(extra)   if extra   else 'none'}}")
    if missing:
        all_pass = False
    print()

    if not common:
        print("ERROR: No common columns to compare.  Check column naming.", file=sys.stderr)
        sys.exit(1)

    # ── Auto-detect key columns ───────────────────────────────────────────────
    if not key_cols:
        key_cols = _auto_detect_keys(common)
        if key_cols:
            print(f"  Auto-detected key columns: {{', '.join(key_cols)}}")
        else:
            print("  No key columns detected — using positional row alignment.")
    print()

    # ── Row-level join ────────────────────────────────────────────────────────
    valid_keys = [k for k in key_cols if k in common]
    if valid_keys:
        try:
            merged = pd.merge(
                df_exp[common].add_suffix("__exp"),
                df_act[common].add_suffix("__act"),
                left_on  =[k + "__exp" for k in valid_keys],
                right_on =[k + "__act" for k in valid_keys],
                how="outer",
                indicator=True,
            )
        except Exception as e:
            print(f"WARNING: Key-based join failed ({{e}}). Falling back to positional.", file=sys.stderr)
            merged = _positional_merge(df_exp, df_act, common)
            valid_keys = []
    else:
        merged = _positional_merge(df_exp, df_act, common)

    # ── Field-level comparison ────────────────────────────────────────────────
    print(_section("FIELD-LEVEL COMPARISON"))
    header = f"  {{\'Column\':<30}} {{\'Match Rate\':>12}}  {{\'Null Rate (exp/act)\':>22}}  Status"
    print(header)
    print("  " + "─" * (len(header) - 2))

    field_results: list[dict] = []
    total_rows_compared = len(merged)

    for col in common:
        if col in valid_keys:
            continue  # skip key columns — they were used for joining

        exp_col = col + "__exp" if valid_keys else col + "__exp"
        act_col = col + "__act" if valid_keys else col + "__act"

        if exp_col not in merged.columns or act_col not in merged.columns:
            continue

        s_exp = merged[exp_col]
        s_act = merged[act_col]

        null_exp = s_exp.isna().mean() * 100
        null_act = s_act.isna().mean() * 100

        # Compare values — try numeric first, fall back to string
        match_rate, mismatches, heuristic = _compare_series(s_exp, s_act, col)

        if col in ignore_cols:
            status = "⊘ SKIPPED"
            status_str = f"{{status:10}}"
        elif match_rate == 100.0:
            status_str = "✓ PASS"
        elif match_rate >= args.threshold:
            status_str = f"⚠ WARN  ({{mismatches}} mismatches)"
            all_pass = False  # warn still fails unless within threshold overall
        else:
            status_str = f"✗ FAIL  ({{mismatches}} mismatches)"
            all_pass = False

        print(
            f"  {{col:<30}} {{match_rate:>11.2f}}%  "
            f"{{null_exp:>9.1f}}% / {{null_act:<9.1f}}%  {{status_str}}"
        )

        field_results.append({{
            "col": col, "match_rate": match_rate,
            "mismatches": mismatches, "heuristic": heuristic,
            "exp": s_exp, "act": s_act,
        }})

    print()

    # ── Mismatch sample ───────────────────────────────────────────────────────
    mismatch_cols = [r for r in field_results if r["mismatches"] > 0]
    if mismatch_cols:
        print(_section(f"MISMATCH SAMPLE (up to {{MISMATCH_LIMIT}} rows per column)"))
        for r in mismatch_cols[:5]:  # show up to 5 columns
            col      = r["col"]
            s_exp    = r["exp"]
            s_act    = r["act"]
            bad_mask = s_exp.fillna("__NULL__") != s_act.fillna("__NULL__")
            sample   = merged[bad_mask].head(MISMATCH_LIMIT)
            print(f"  Column: {{col}}  ({{r['mismatches']}} total mismatches)")
            if r["heuristic"]:
                print(f"  Likely cause: {{r['heuristic']}}")
            # Print key + differing values
            display_keys = [k + "__exp" for k in valid_keys] if valid_keys else []
            exp_vals = sample[col + "__exp"].tolist()
            act_vals = sample[col + "__act"].tolist()
            for i, (ev, av) in enumerate(zip(exp_vals[:MISMATCH_LIMIT], act_vals[:MISMATCH_LIMIT])):
                print(f"    Row {{i+1:>3}}:  expected={{repr(ev):<20}}  actual={{repr(av)}}")
            print()

    # ── Overall result ────────────────────────────────────────────────────────
    print(_section("OVERALL RESULT"))

    # Compute overall row match rate across all non-key columns
    if field_results:
        overall_match = sum(r["match_rate"] for r in field_results) / len(field_results)
    else:
        overall_match = 100.0

    print(f"  Row match rate : {{overall_match:.2f}}% (threshold: {{args.threshold}}%)")

    if all_pass and overall_match >= args.threshold:
        print("  ✓ PASS")
    else:
        print("  ✗ FAIL")

    # Print heuristic warnings
    heuristics = [r["heuristic"] for r in field_results if r["heuristic"]]
    if heuristics:
        print()
        print("  Warnings:")
        for h in heuristics:
            print(f"  - {{h}}")

    print()
    sys.exit(0 if (all_pass and overall_match >= args.threshold) else 1)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Compare Informatica golden output CSV against generated-code output CSV.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--expected",       required=True,  help="Informatica golden-output CSV")
    p.add_argument("--actual",         required=True,  help="Generated-code output CSV")
    p.add_argument("--threshold",      type=float, default=100.0,
                   help="Minimum match %% to pass (default: 100.0)")
    p.add_argument("--key-columns",    default="",
                   help="Comma-separated key columns for row join")
    p.add_argument("--ignore-columns", default="",
                   help="Comma-separated columns to exclude from comparison")
    return p.parse_args()


def _auto_detect_keys(columns: list[str]) -> list[str]:
    """Heuristically pick key columns from common column names."""
    import re
    candidates = [c for c in columns
                  if re.search(r"(_ID|_KEY|_SK|_PK)$", c, re.IGNORECASE)]
    return candidates[:2]  # use at most 2 key columns


def _positional_merge(
    df_exp: "pd.DataFrame",
    df_act: "pd.DataFrame",
    common: list[str],
) -> "pd.DataFrame":
    """Align rows positionally (by index) when no key columns are available."""
    min_len = min(len(df_exp), len(df_act))
    merged  = pd.DataFrame()
    for col in common:
        merged[col + "__exp"] = df_exp[col].iloc[:min_len].reset_index(drop=True)
        merged[col + "__act"] = df_act[col].iloc[:min_len].reset_index(drop=True)
    return merged


def _compare_series(
    s_exp: "pd.Series",
    s_act: "pd.Series",
    col_name: str,
) -> tuple[float, int, str]:
    """
    Compare two string-typed Series.  Returns (match_rate_pct, mismatch_count, heuristic).
    Tries numeric comparison with tolerance; falls back to string equality.
    """
    import re

    total = len(s_exp)
    if total == 0:
        return 100.0, 0, ""

    heuristic = ""

    # Try numeric comparison
    try:
        n_exp = pd.to_numeric(s_exp, errors="raise")
        n_act = pd.to_numeric(s_act, errors="raise")
        # Both numeric — compare with tolerance
        both_null  = n_exp.isna() & n_act.isna()
        one_null   = n_exp.isna() ^ n_act.isna()
        both_valid = ~n_exp.isna() & ~n_act.isna()
        close      = both_valid & (
            abs(n_exp - n_act) <= FLOAT_ATOL + FLOAT_RTOL * abs(n_exp)
        )
        matches    = both_null.sum() + close.sum()
        mismatches = int(total - matches - one_null.sum())
        if mismatches > 0:
            avg_diff = (n_exp - n_act).abs().dropna().mean()
            if avg_diff < 0.01:
                heuristic = (
                    f"{{col_name}}: Float rounding ({avg_diff:.6f} avg diff) — "
                    "review IIF/arithmetic expression translation"
                )
        match_rate = 100.0 * matches / total
        return match_rate, mismatches, heuristic
    except (ValueError, TypeError):
        pass

    # Try date comparison
    try:
        d_exp = pd.to_datetime(s_exp, errors="raise", infer_datetime_format=True)
        d_act = pd.to_datetime(s_act, errors="raise", infer_datetime_format=True)
        matches    = (d_exp == d_act) | (d_exp.isna() & d_act.isna())
        mismatches = int((~matches).sum())
        if mismatches > 0:
            heuristic = (
                f"{{col_name}}: Date format mismatch — "
                "check TO_DATE format string against target stack"
            )
        match_rate = 100.0 * matches.sum() / total
        return match_rate, mismatches, heuristic
    except Exception:
        pass

    # String comparison
    s_exp_norm = s_exp.fillna("__NULL__").str.strip()
    s_act_norm = s_act.fillna("__NULL__").str.strip()
    matches    = s_exp_norm == s_act_norm

    # Check if whitespace trimming accounts for differences
    raw_exp = s_exp.fillna("__NULL__")
    raw_act = s_act.fillna("__NULL__")
    whitespace_diffs = ((raw_exp != raw_act) & (s_exp_norm == s_act_norm)).sum()

    mismatches = int((~matches).sum())
    if mismatches > 0 and whitespace_diffs > 0:
        heuristic = (
            f"{{col_name}}: LTRIM/RTRIM — Python strips both ends by default; "
            "Informatica may strip only one end"
        )
    match_rate = 100.0 * matches.sum() / total
    return match_rate, mismatches, heuristic


def _banner(title: str) -> str:
    bar = "═" * 63
    return f"\\n{{bar}}\\n  {{title}}\\n{{bar}}"


def _section(title: str) -> str:
    return f"{{title}}\\n  {{'-' * len(title)}}"


# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    main()
'''
